### ISSUE TITLE
Add interactive prompt

### ISSUE THREAD

**Issue by brpaz** [greybax/generator-badges#2]
This generator is a great idea, but do you plan do add support for more badges? You can find lots of badges at http://shields.io/

I plan to add some more like Codeship and Scrunitizer.

Probably a personal preference, but I think would be simple to use your generator with an interactive prompt asking for the project, user, and badges  (selecting from a list)  instead of specifying directly via the generator options.

**Comment by greybax** [comment]
@brpaz Thank you for your feedback! I'm going to add more badges and also I'm ok for new PRs. Feel free for contributions :smile:

**Comment by greybax** [comment]
- [x] add Codeship and Scrunitizer. Fixed in commit b149ce894770327f999ea98f8a1ccded8217d818
- [x] add interactive prompt asking for the project, user and badges (selecting from a list)

**Comment by greybax** [comment]
Added interactive prompt. In future going to take all badges from shields.io.
Renamed this issue to "Add interactive prompt" and closed it. Will create another task for badges from shields.io
